name: Deployment
on:
  push:
    branches:
    - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Get code
      uses: actions/checkout@v4
    - name: Load & cache dependencies
      id: cache-deps
      uses: ./.github/actions/cached-deps # Composite Action
      with:
        caching: 'false' # Disable caching for lint job. caching is defined in inputs in action.yml
    - name: Output information
      # used-cache is in outputs of the Composite Action cached-deps
      run: echo "Cache used? ${{ steps.cache-deps.outputs.used-cache }}"
    - name: Lint code
      run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Get code
      uses: actions/checkout@v4
    - name: Load & cache dependencies
      uses: ./.github/actions/cached-deps # Composite Action
    - name: Test code
      id: run-tests
      run: npm run test
    - name: Upload test report
      if: failure() && steps.run-tests.outcome == 'failure'
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: test.json
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Get code
      uses: actions/checkout@v4
    - name: Load & cache dependencies
      uses: ./.github/actions/cached-deps # Composite Action
    - name: Build website
      run: npm run build
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-files
        path: dist
  deploy:
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Get code
      uses: actions/checkout@v4
    - name: Get build artifacts
      uses: actions/download-artifact@v4
      with:
        name: dist-files
        path: ./dist
    - name: Output contents
      run: ls
    - name: Get AWS permissions
      uses: aws-actions/configure-aws-credentials@v4
      with:
        #role-to-assume: arn:aws:iam::450226343468:role/GitHubDemo1
        role-to-assume: arn:aws:iam::767397911094:role/GitHubActions
        aws-region: eu-north-1 # us-east-1
    - name: Deploy site
      id: deploy
      #uses: ./.github/actions/deploy-s3-docker
      uses: ./.github/actions/deploy-s3-javascript
      with:
        bucket: mjhmhouben # gha-security-hosting-demo
        dist-folder: ./dist
        bucket-region: eu-north-1 # us-east-2
    - name: Output information
      # deploy refers to id deploy at line 79
      run: |
        echo "Live URL: ${{ steps.deploy.outputs.website-url }}"
  #information:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Get code # Deze step is noodzakelijk want de code moet beschikbaar zijn voor de JavaScript Action.
  #      uses: actions/checkout@v3
  #    - name: Run custom JavaScript Action
  #      uses: ./.github/actions/deploy-s3-javascript # JavaScript Action
