name: Dependabot PR Approval and Merge
# This workflow automatically approves and merges pull requests created by Dependabot.

on:
  push:
    branches:
    - main
  pull_request:


permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

  dependabot:
    needs: [ build ] # <-- important!
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'}}
    steps:
    - id: metadata
      uses: dependabot/fetch-metadata@v2
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
    - run: |
        gh pr merge --squash --auto "$PR_URL"
      env:
        PR_URL: ${{github.event.pull_request.html_url}}
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

# Maak een Personal Access Token (PAT) aan
# - Ga naar GitHub Settings > Developer settings > Personal access tokens.
# - Maak een nieuw token aan met minimaal de scopes: repo, workflow, en pull_request.
# - Sla het token veilig op.

# Voeg het token toe als secret in je repository
# - Ga naar je repository > Settings > Secrets and variables > Actions.
# - Voeg een nieuwe secret toe, bijvoorbeeld GH_PAT.

# Gebruik het token in je workflow
# - Vervang ${{ secrets.GITHUB_TOKEN }} door ${{ secrets.GH_PAT }} in je workflow waar je goedkeuring wilt uitvoeren.
