# Automatically approves and merges Dependabot pull requests for patch and minor updates
name: Dependabot Auto-Approval

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

# Minimal permissions following principle of least privilege
permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot-auto-approve:
    # Only run for Dependabot PRs
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Fetch Dependabot metadata
      id: metadata
      uses: dependabot/fetch-metadata@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        alert-lookup: true
        compat-lookup: true

    - name: Add labels based on dependency type
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const labels = [];

          // Add dependency type label
          if ('${{ steps.metadata.outputs.dependency-type }}' === 'direct:production') {
            labels.push('production');
          } else if ('${{ steps.metadata.outputs.dependency-type }}' === 'direct:development') {
            labels.push('development');
          }

          // Add update type label
          if ('${{ steps.metadata.outputs.update-type }}' === 'version-update:semver-patch') {
            labels.push('patch');
          } else if ('${{ steps.metadata.outputs.update-type }}' === 'version-update:semver-minor') {
            labels.push('minor');
          } else if ('${{ steps.metadata.outputs.update-type }}' === 'version-update:semver-major') {
            labels.push('major');
          }

          // Add labels if any exist
          if (labels.length > 0) {
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: labels
            });
          }

    - name: Auto-approve patch and minor updates
      if: |
        steps.metadata.outputs.update-type == 'version-update:semver-patch' || 
        steps.metadata.outputs.update-type == 'version-update:semver-minor'
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          console.log(`Auto-approving ${{ steps.metadata.outputs.update-type }} update for ${{ steps.metadata.outputs.dependency-names }}`);

          await github.rest.pulls.createReview({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number,
            event: 'APPROVE',
            body: '✅ Auto-approved ${{ steps.metadata.outputs.update-type }} dependency update'
          });

    - name: Enable auto-merge for approved updates
      if: |
        steps.metadata.outputs.update-type == 'version-update:semver-patch' || 
        steps.metadata.outputs.update-type == 'version-update:semver-minor'
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          console.log('Enabling auto-merge for approved update...');

          await github.rest.pulls.merge({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number,
            merge_method: 'squash'
          });

    - name: Comment on major updates
      if: steps.metadata.outputs.update-type == 'version-update:semver-major'
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: `🚨 **Major version update detected**

          This PR contains a major version update for \`${{ steps.metadata.outputs.dependency-names }}\` which may include breaking changes.

          **Please review carefully before merging:**
          - Check the changelog/release notes
          - Verify compatibility with existing code
          - Run comprehensive tests

          This PR will not be auto-merged and requires manual review.`
          });
