name: 'Deploy to AWS S3'
description: 'Deploy a static website via AWS S3.'
inputs:
  bucket:
    # mjhmhouben
    description: 'The S3 bucket name.'
    required: true
  bucket-region:
    # eu-north-1
    description: 'The region of the S3 bucket.'
    required: false
    default: 'us-east-1'
  dist-folder:
    description: 'The folder containing the deployable files.'
    required: true
outputs:
  website-url:
    description: 'The URL of the deployed website.'
runs:
  using: 'node16' # JavaScript Action
  #pre: 'pre.js' # Name of the file that should be executed before main
  main: 'main.js' # Name of the file that should be executed
  #post: 'post.js' # Name of the file that should be executed after main
